# version format
version: 2.4-{build}

# pull request template
pull_requests:
  do_not_increment_build_number: true

# vm template
image: Visual Studio 2022

# environment variables
environment:
  EnableNuGetPackageRestore: true

# install dependencies
install:
- ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
- cd %APPVEYOR_BUILD_FOLDER%
- git submodule update --init --recursive

# pre-build script
before_build:
- nuget restore

# build step
build_script:
  - dotnet restore
  - msbuild MPF\MPF.csproj -property:TargetFramework=net48 
  #- dotnet build MPF\MPF.csproj --framework net6.0
  - dotnet build MPF.Check\MPF.Check.csproj --framework net48
  - dotnet publish MPF.Check\MPF.Check.csproj --framework net6.0 --runtime win-x86 --self-contained true -p:PublishSingleFile=true
  - dotnet publish MPF.Check\MPF.Check.csproj --framework net6.0 --runtime win-x64 --self-contained true -p:PublishSingleFile=true
  - dotnet publish MPF.Check\MPF.Check.csproj --framework net6.0 --runtime linux-x64 --self-contained true -p:PublishSingleFile=true
  - dotnet publish MPF.Check\MPF.Check.csproj --framework net6.0 --runtime osx-x64 --self-contained true -p:PublishSingleFile=true

# post-build step
after_build:

# Aaru
- ps: appveyor DownloadFile https://github.com/aaru-dps/Aaru/releases/download/v5.3.2/aaru-5.3.2_windows_x64.zip
- 7z x aaru-5.3.2_windows_x64.zip -oMPF\bin\Debug\net48\Programs\Aaru *
#- 7z x aaru-5.3.2_windows_x64.zip -oMPF\bin\Debug\net6.0\Programs\Aaru *

# dd for Windows
- ps: appveyor DownloadFile http://www.chrysocome.net/downloads/8ab730cd2a29e76ddd89be1f99357942/dd-0.6beta3.zip
- 7z e dd-0.6beta3.zip -oMPF\bin\Debug\net48\Programs\DD *
#- 7z e dd-0.6beta3.zip -oMPF\bin\Debug\net6.0\Programs\DD *

# DiscImageCreator
- ps: appveyor DownloadFile https://github.com/saramibreak/DiscImageCreator/files/9536254/DiscImageCreator_20220909.zip
- 7z e DiscImageCreator_20220909.zip -oMPF\bin\Debug\net48\Programs\Creator Release_ANSI\*
#- 7z e DiscImageCreator_20220909.zip -oMPF\bin\Debug\net6.0\Programs\Creator Release_ANSI\*

# Redumper
- ps: appveyor DownloadFile https://github.com/superg/redumper/releases/download/build_81/redumper-2022.12.13_build81-win64.zip
- 7z e redumper-2022.12.13_build81-win64.zip -oMPF\bin\Debug\net48\Programs\Redumper redumper-2022.12.13_build81-win64\bin\*
#- 7z e redumper-2022.12.13_build81-win64.zip -oMPF\bin\Debug\net6.0\Programs\Redumper redumper-2022.12.13_build81-win64\bin\*

# Subdump
- ps: appveyor DownloadFile https://archive.org/download/subdump_fua_0x28/subdump_fua_0x28.zip
- 7z e subdump_fua_0x28.zip -oMPF\bin\Debug\net48 *
- mkdir MPF\bin\Debug\net48\Programs\Subdump
- mv MPF\bin\Debug\net48\subdump_fua_0x28.exe MPF\bin\Debug\net48\Programs\Subdump\subdump.exe
#- 7z e subdump_fua_0x28.zip -oMPF\bin\Debug\net6.0 *
#- mkdir MPF\bin\Debug\net6.0\Programs\Subdump
#- mv MPF\bin\Debug\net6.0\subdump_fua_0x28.exe MPF\bin\Debug\net6.0\Programs\Subdump\subdump.exe

# MPF
- cd %APPVEYOR_BUILD_FOLDER%\MPF\bin\Debug\net48
- 7z a -tzip %APPVEYOR_BUILD_FOLDER%\MPF_net48.zip *
#- cd %APPVEYOR_BUILD_FOLDER%\MPF\bin\Debug\net6.0
#- 7z a -tzip %APPVEYOR_BUILD_FOLDER%\MPF_net6.0.zip *

# MPF.Check
- cd %APPVEYOR_BUILD_FOLDER%\MPF.Check\bin\Debug\net48
- 7z a -tzip %APPVEYOR_BUILD_FOLDER%\MPF.Check_net48.zip *
- cd %APPVEYOR_BUILD_FOLDER%\MPF.Check\bin\Debug\net6.0\win-x86\publish\
- 7z a -tzip %APPVEYOR_BUILD_FOLDER%\MPF.Check_net6.0_win-x86.zip *
- cd %APPVEYOR_BUILD_FOLDER%\MPF.Check\bin\Debug\net6.0\win-x64\publish\
- 7z a -tzip %APPVEYOR_BUILD_FOLDER%\MPF.Check_net6.0_win-x64.zip *
- cd %APPVEYOR_BUILD_FOLDER%\MPF.Check\bin\Debug\net6.0\linux-x64\publish\
- 7z a -tzip %APPVEYOR_BUILD_FOLDER%\MPF.Check_net6.0_linux-x64.zip *
- cd %APPVEYOR_BUILD_FOLDER%\MPF.Check\bin\Debug\net6.0\osx-x64\publish\
- 7z a -tzip %APPVEYOR_BUILD_FOLDER%\MPF.Check_net6.0_osx-x64.zip *

# success/failure tracking
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL

# artifact linking
artifacts:
- path: MPF_net48.zip
  name: MPF (.NET Framework 4.8)
#- path: MPF_net6.0.zip
#  name: MPF (.NET 6.0)

- path: MPF.Check_net48.zip
  name: MPF Check (.NET Framework 4.8)
- path: MPF.Check_net6.0_win-x86.zip
  name: MPF.Check (.NET 6.0, Windows x86)
- path: MPF.Check_net6.0_win-x64.zip
  name: MPF.Check (.NET 6.0, Windows x64)
- path: MPF.Check_net6.0_linux-x64.zip
  name: MPF.Check (.NET 6.0, Linux x64)
- path: MPF.Check_net6.0_osx-x64.zip
  name: MPF.Check (.NET 6.0, OSX x64)